# LICENSE

# CloudFormation template to create publishing pipeline for boto3/botocore
# packages as Lambda layers in all support AWS regions. It will create all
# resources to monitor for boto3 changes, build new layers, and publish the
# new details via GitHub README file and via public API Gateway request.

# Prerequisites:
# - github repo
# - GitHub personal access token for repo allowing full permissions (see: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)

# To create
# - codebuild project
# - access role for project
#   - defaults from a codebuild (non-VPC) role, PLUS:
#   - publish lambda layer for all regions
#   - dynamodb table access

# dynamodb table for all published entries

# CWE with lambda to detect new version of boto3 and the initiate CB project
# - lambda
# - CWE
# - role for lambda
# - CWE to invoke lmabda

# apig with resources:
# - return latest arn for requested region
# - return arn for specifc region/version

# cloudtrail trail to log all APIG requests and Lamda layer access

---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Automates discovery and build of Lambda layers for latest versions of boto3 and
  botocore python packages. Publishes updates to GitHub repo and accessible via
  API Gateway

Parameters:
  GitHubRepo:
    Type: String
    Description: Public GitHub repository for updating main README.md file
    Default: https://github.com/USERNAME/REPO
  GitHubAccessToken:
    Type: String
    Description: AWS System Manager GitHub access token parameter to pass to build jobs (NOT THE ACTUAL TOKEN)
    Default: /CodeBuild/KEYNAME

Resources:
  CodeBuildProject:
      Type: "AWS::CodeBuild::Project"
      Properties:
        TimeoutInMinutes: 15
        Artifacts: 
          Type: "NO_ARTIFACTS"
        Cache: 
          Type: "NO_CACHE"
        Description: "Build boto3 packages and publish"
        Environment: 
          ComputeType: "BUILD_GENERAL1_SMALL"
          Image: "aws/codebuild/docker:18.09.0"
          Type: "LINUX_CONTAINER"
          PrivilegedMode: true
          EnvironmentVariables:
          - Name: GITHUB_TOKEN
            Type: PARAMETER_STORE
            Value: !Ref GitHubAccessToken
        ServiceRole: !GetAtt CodeBuildServiceRole.Arn
        Name: !Join
                - "_"
                -
                  - !Join ["", !Split ["-",  !Ref "AWS::StackName"] ]
                  - "boto3_builder"
        Source: 
          Type: "GITHUB"
          Auth:
            Type: "OAUTH"
            #Resource: !Ref GitHubAccessToken
          GitCloneDepth: 1
          InsecureSsl: "false"
          Location: "https://github.com/gadams999/lambda-layer-boto3.git"
          BuildSpec: "codebuild/buildspec.yml"
          ReportBuildStatus: "false"
  
  # Roles and policies
  CodeBuildServiceRole:
    # Default permissions to run CodeBuild jos
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: CodeBuildCloudWatchLogs
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - !Join
              - ""
              -
                - "arn:aws:logs:"
                - !Ref "AWS::Region"
                - ":"
                - !Ref "AWS::AccountId"
                - ":log-group:/aws/codebuild/"
                - !Join ["", !Split ["-",  !Ref "AWS::StackName"] ]
                # leading underscore as not using same Join/Split as in CodeBuild resource
                - "_boto3_builder"
            - !Join
              - ""
              -
                - "arn:aws:logs:"
                - !Ref "AWS::Region"
                - ":"
                - !Ref "AWS::AccountId"
                - ":log-group:/aws/codebuild/"
                - !Join ["", !Split ["-",  !Ref "AWS::StackName"] ]
                # leading underscore as not using same Join/Split as in CodeBuild resource
                - "_boto3_builder:*"
          - Sid: CodePipelineS3Access
            Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
            Resource:
            - "arn:aws:s3:::codepipeline-us-west-2-*"
          - Sid: FullSSMAccess
            Effect: Allow
            Action:
            - ssm:GetParameters
            Resource:
            - !Join
              - ""
              -
                - "arn:aws:ssm:"
                - !Ref "AWS::Region"
                - ":"
                - !Ref "AWS::AccountId"
                - ":parameter/CodeBuild/*"

